### ISSUE TITLE
Allow curdle to be installed in directories below the document root

### ISSUE THREAD

**Issue by Natorator** [sitilge/curdle#27]
Would you be interested in a PR for this? 

I already have this working in project I'm using Curdle for, but it's messy. I could do it a slightly less messy way with a global BASE_PATH constant. 

...or I could do it the more properly dependency-injected way that refactors the router, frontcontroller, businessmodel and urlmodel classes to accept an injected $basepath. 

Preferences?

**Comment by sitilge** [comment]
Hi Natorator,

If by `PR` you mean spreading the word then I am all in :+1: .

Please, see the comments under pull requests for more info.

**Comment by sitilge** [comment]
@Natorator 

Good job, merged.
