### ISSUE TITLE
Demo Errrors

### ISSUE THREAD

**Issue by k3bra** [sitilge/curdle#6]
I believe you don't want anyone be able to edit or delete products from the demo in that case I think you should show a nice message instead of this error.

HY000	Exception	SQLSTATE[HY000]: General error: 8 attempt to write a readonly database	/var/www/curdle.sitilge.id.lv/app/Models/AdminModel.php	447

Keep the good work

**Comment by sitilge** [comment]
Thank you for idea,

The error message is in development and will be shipped soon.
